In [1]:
import pandas as pd

In [11]:
pd.read_excel('vlookup-all-matching-results.xlsx')

,Unnamed: 0,Unnamed: 1,VLOOKUP Multiple Results,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Sales person,Carla Molina,NaN,NaN,NaN,Sales Person,Geography,Product,Amount,Units,NaN,Want more? Check out my LOOKUP course:
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ram Mahesh,New Zealand,70% Dark Bites,1624,114,NaN,NaN
4,NaN,NaN,Amount,9632,NaN,NaN,NaN,Brien Boise,USA,Choco Coated Almonds,6706,459,NaN,NaN
5,NaN,NaN,Amount (with XLOOKUP),9632,NaN,NaN,NaN,Husein Augar,USA,Almond Choco,959,147,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carla Molina,Canada,Drinking Coco,9632,288,NaN,NaN
7,NaN,NaN,Product(s),Amount(s),NaN,NaN,NaN,Curtice Advani,UK,White Choc,2100,414,NaN,NaN
8,NaN,NaN,Drinking Coco,9632,NaN,NaN,NaN,Ram Mahesh,USA,Peanut Butter Cubes,8869,432,NaN,NaN
9,NaN,NaN,After Nines,336,NaN,NaN,NaN,Curtice Advani,Australia,Smooth Sliky Salty,2681,54,NaN,NaN
10,NaN,NaN,Raspberry Choco,2114,NaN,NaN,NaN,Brien Boise,USA,After Nines,5012,210,NaN,NaN
11,NaN,NaN,Milk Bars,10311,NaN,NaN,NaN,Ches Bonnell,Australia,50% Dark Bites,1281,75,NaN,NaN
12,NaN,NaN,85% Dark Bars,6398,NaN,NaN,NaN,Ram Mahesh,UK,After Nines,5817,12,NaN,NaN
13,NaN,NaN,50% Dark Bites,3976,NaN,NaN,NaN,Gigi Bohling,New Zealand,50% Dark Bites,4991,12,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barr Faughny,UK,White Choc,1785,462,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gunar Cockshoot,New Zealand,Eclairs,3983,144,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Husein Augar,Australia,Mint Chip Choco,2646,120,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barr Faughny,India,Milk Bars,252,54,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gunar Cockshoot,USA,White Choc,2464,234,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gunar Cockshoot,USA,Manuka Honey Choco,2114,66,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Curtice Advani,New Zealand,Smooth Sliky Salty,7693,87,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gigi Bohling,India,Orange Choco,15610,339,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carla Molina,India,After Nines,336,144,NaN,NaN
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barr Faughny,UK,Orange Choco,9443,162,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Husein Augar,India,Fruit & Nut Bars,8155,90,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brien Boise,Australia,Fruit & Nut Bars,1701,234,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oby Sorrel,Australia,After Nines,2205,141,NaN,NaN
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brien Boise,New Zealand,99% Dark & Pure,1771,204,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carla Molina,USA,Raspberry Choco,2114,186,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carla Molina,Canada,Milk Bars,10311,231,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gunar Cockshoot,UK,Mint Chip Choco,21,168,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oby Sorrel,USA,Orange Choco,1974,195,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gigi Bohling,Canada,Fruit & Nut Bars,6314,15,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Oby Sorrel,New Zealand,Fruit & Nut Bars,4683,30,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carla Molina,New Zealand,85% Dark Bars,6398,102,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Barr Faughny,USA,99% Dark & Pure,553,15,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Brien Boise,UK,70% Dark Bites,7021,183,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Carla Molina,UK,50% Dark Bites,3976,72,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Curtice Advani,Australia,Organic Choco Syrup,1134,282,NaN,NaN

In [12]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [13]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2023-07-11,1689033602,0.0445
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2023-07-11,1689033602,1.0400
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2023-07-11,1689033602,1.1500
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2023-07-11,1689033602,4.6800
ANG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2023-07-11,1689033602,0.0217
...,...,...,...,...,...,...,...
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2023-07-11,1689033602,1.3200
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2023-07-11,1689033602,3.0300
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2023-07-11,1689033602,0.2280
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2023-07-11,1689033602,0.2200
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2023-07-11,1689033602,64.0800

# WORKING WITH SQL